/*
 * DaDaPush Public API
 *
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * API version: v1
 * Contact: contacts@dadapush.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dadapushclient

import (
	"fmt"
	"testing"
)

func TestDaDaPushMessageApiService_CreateMessage(t *testing.T) {
	configuration := NewConfiguration()
	//configuration.BasePath="http://127.0.0.1:8080"
	apiClient := NewAPIClient(configuration)
	var body MessagePushRequest
	body.Title = "Good News!"
	body.Content = "Good News! DaDaPush releasing new version"
	body.NeedPush = true
	var action Action
	action.Name = "view"
	action.Type = "link"
	action.Url = "https://www.dadapush.com/"
	body.Actions = []Action{action}
	response, i, e := apiClient.DaDaPushMessageApi.CreateMessage(nil, body, "ctb3lwO6AeiZOwqZgp8BE8980FdNgp0cp6MCf")
	fmt.Println(response)
	fmt.Println(i)
	fmt.Println(e)
}

func TestDaDaPushMessageApiService_DeleteMessage(t *testing.T) {
	configuration := NewConfiguration()
	//configuration.BasePath="http://127.0.0.1:8080"
	apiClient := NewAPIClient(configuration)
	messageId := 227870
	response, i, e := apiClient.DaDaPushMessageApi.DeleteMessage(nil, int64(messageId), "ctb3lwO6AeiZOwqZgp8BE8980FdNgp0cp6MCf")
	fmt.Println(response)
	fmt.Println(i)
	fmt.Println(e)
}

func TestDaDaPushMessageApiService_GetMessage(t *testing.T) {
	configuration := NewConfiguration()
	//configuration.BasePath="http://127.0.0.1:8080"
	apiClient := NewAPIClient(configuration)
	messageId := 227870
	response, i, e := apiClient.DaDaPushMessageApi.GetMessage(nil, int64(messageId), "ctb3lwO6AeiZOwqZgp8BE8980FdNgp0cp6MCf")
	fmt.Println(response)
	fmt.Println(i)
	fmt.Println(e)
}

func TestDaDaPushMessageApiService_GetMessages(t *testing.T) {
	configuration := NewConfiguration()
	//configuration.BasePath="http://127.0.0.1:8080"
	apiClient := NewAPIClient(configuration)
	page := 1
	pageSize := 10
	response, i, e := apiClient.DaDaPushMessageApi.GetMessages(nil, int32(page), int32(pageSize), "ctb3lwO6AeiZOwqZgp8BE8980FdNgp0cp6MCf")
	fmt.Println(response)
	fmt.Println(i)
	fmt.Println(e)
}
