/*
 * DaDaPush Public API
 *
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * API version: v1
 * Contact: contacts@dadapush.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dadapush-client

type Action struct {
	// action button name
	Name string `json:"name"`
	// fix value: link
	Type string `json:"type"`
	// action url
	Url string `json:"url"`
}
