/*
 * DaDaPush Public API
 *
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * API version: v1
 * Contact: contacts@dadapush.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dadapush-go-client

type MessageObject struct {
	// action size range is 0,3
	Actions []Action `json:"actions,omitempty"`
	ChannelName string `json:"channelName"`
	Content string `json:"content"`
	CreatedAt string `json:"createdAt"`
	Id int64 `json:"id"`
	Title string `json:"title"`
}
